version: "3.3"

services:
  gestion-turnos:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9091:8081
  mysql:
    build:
      context: .
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"