# cat docker-compose.yml
version: '3.3'
services:
  ### MySQL Container
  mysql:
    image: mysql:8.0.31
    restart: unless-stopped
    env_file: ./.env
    environment:
        - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
        - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - db:/var/lib/mysql
  app:
    env_file: ./.env
    depends_on:
      - mysql
    build: ../projecto_sin_cambios_yml
    restart: on-failure
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/${MYSQL_DATABASE}?useSSL=false",
          "spring.datasource.username" : "${MYSQL_USER}",
          "spring.datasource.password" : "${MYSQL_PASSWORD}",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
          "server.error.whitelabel.enabled" : "true"
          "paypal.mode" : "sandbox"
          "paypal.client.id" : "<paypalClientId>"
          "paypal.client.secret" : "<paypalClientSecret>"
          "spring.servlet.multipart.max-file-size" : "128KB"
          "spring.servlet.multipart.max-request-size" : "128KB"
          "spring.servlet.multipart.enabled" : "true"
          
          
          
          "spring.mail.protocol" : "smtp"
          "spring.mail.host" : "smtp.mailtrap.io"
          "spring.mail.port" : "2525"
          "spring.mail.properties.mail.smtp.auth"  :  "true"
          "spring.mail.properties.mail.smtp.starttls.enable"  :  "true"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: